'use strict';
let addressMap,addressMarker;
state.addresses=[]; state.selectedAddress=null; state.deliveryQuote=null;
config.paths.addresses='/addresses'; config.paths.quote='/delivery/quote';
async function refreshDeliveryQuote(restaurantId){if(!restaurantId||!state.location)throw new Error('Choose a restaurant and delivery address');try{state.deliveryQuote=await request(config.paths.quote,{method:'POST',body:JSON.stringify({restaurantId,latitude:+state.location.latitude,longitude:+state.location.longitude})});renderPrice();return state.deliveryQuote}catch(e){state.deliveryQuote=null;renderPrice();throw new Error(`Checkout blocked: ${e.message}`)}}

function setAddressPoint(lat,lon,label='Pinned location'){
  const latitude=Number(lat),longitude=Number(lon); const form=$('#address-form');
  form.latitude.value=latitude; form.longitude.value=longitude;
  $('#address-coordinates').textContent=`${label} · ${latitude.toFixed(6)}, ${longitude.toFixed(6)}`;
  if(addressMap){addressMap.setView([latitude,longitude],16);addressMarker?addressMarker.setLatLng([latitude,longitude]):addressMarker=L.marker([latitude,longitude]).addTo(addressMap)}
}
function initAddressMap(){if(addressMap||!window.L)return;const loc=state.location||{latitude:12.9716,longitude:77.5946};addressMap=L.map('address-map').setView([loc.latitude,loc.longitude],13);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(addressMap);addressMap.on('click',e=>setAddressPoint(e.latlng.lat,e.latlng.lng,'Map pin'))}
function useAddress(address,discover=true){state.selectedAddress=address;saveLocation(Number(address.latitude),Number(address.longitude),`${address.label} · ${address.addressLine}`);if(discover)discoverNearby(Number(address.latitude),Number(address.longitude));renderAddresses();renderCheckoutAddress();$('#address-modal').close();if(state.returnToOrderAfterAddress){state.returnToOrderAfterAddress=false;$('#order-modal').showModal();const restaurantId=Number($('#order-form').restaurantId.value);if(restaurantId)refreshDeliveryQuote(restaurantId).catch(x=>{$('#order-form .form-error').textContent=x.message})}}
function renderAddresses(){const box=$('#saved-addresses'),addresses=Array.isArray(state.addresses)?state.addresses:[];state.addresses=addresses;box.innerHTML=addresses.length?addresses.map(a=>`<article class="saved-address ${state.selectedAddress?.id===a.id?'selected':''}"><div><b>${esc(a.label)} · ${esc(a.recipient)}</b><small>${esc(a.addressLine)} · ${esc(a.phone)}</small></div><button class="mini select-address" data-id="${a.id}">Deliver here</button><button class="mini danger delete-address" data-id="${a.id}">Delete</button></article>`).join(''):'<div class="address-empty"><b>No saved addresses yet</b><span>Add your first delivery address below.</span></div>';$$('.select-address',box).forEach(b=>b.onclick=async()=>{const a=addresses.find(x=>x.id===+b.dataset.id);if(!a){toast('This address is no longer available');await loadAddresses();return}await request(`/addresses/${a.id}/select`,{method:'PUT'});useAddress(a)});$$('.delete-address',box).forEach(b=>b.onclick=async()=>{await request(`/addresses/${b.dataset.id}`,{method:'DELETE'});await loadAddresses()})}
async function loadAddresses(){if(!state.token){state.addresses=[];state.selectedAddress=null;renderAddresses();return}try{const response=await request(config.paths.addresses);state.addresses=Array.isArray(response)?response:[];state.selectedAddress=state.addresses.find(a=>Boolean(a?.isDefault))||state.addresses[0]||null;if(state.selectedAddress&&!state.location)useAddress(state.selectedAddress,false);renderAddresses()}catch(e){state.addresses=[];state.selectedAddress=null;$('#saved-addresses').innerHTML=`<div class="error-box"><b>Addresses are unavailable</b>${esc(e.message)}</div>`}}
$('#manage-addresses').onclick=()=>{if(!state.token){toast('Sign in to save delivery addresses');$('#auth-modal').showModal();return}$('#address-modal').showModal();setTimeout(()=>{initAddressMap();addressMap?.invalidateSize()},50)};
$('#address-gps').onclick=()=>navigator.geolocation?navigator.geolocation.getCurrentPosition(p=>setAddressPoint(p.coords.latitude,p.coords.longitude,'Live GPS'),e=>toast(e.message),{enableHighAccuracy:true,timeout:10000}):toast('GPS is unavailable; enter the address and choose the map');
$('#geocode-search').onclick=async()=>{const q=$('#map-search').value.trim();if(!q)return;try{const response=await fetch(`https://nominatim.openstreetmap.org/search?format=json&limit=1&q=${encodeURIComponent(q)}`,{headers:{Accept:'application/json'}}),results=await response.json();if(!results.length)throw new Error('Address not found');setAddressPoint(results[0].lat,results[0].lon,'Search result');if(!$('#address-form').addressLine.value)$('#address-form').addressLine.value=results[0].display_name}catch(e){toast(`Map search unavailable: ${e.message}. Use GPS or click the map.`)}};
$('#address-form').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,data=Object.fromEntries(new FormData(form));if(!data.latitude||!data.longitude){$('.form-error',form).textContent='Choose coordinates using GPS, map search, or the map';return}const button=$('button[type="submit"]',form);pending(button,true);try{await request(config.paths.addresses,{method:'POST',body:JSON.stringify({...data,latitude:+data.latitude,longitude:+data.longitude,isDefault:true})});form.reset();await loadAddresses();if(state.selectedAddress)useAddress(state.selectedAddress);toast('Delivery address saved')}catch(x){$('.form-error',form).textContent=x.message}finally{pending(button,false)}};
loadAddresses();
$('#order-form').restaurantId.addEventListener('change',e=>{if(e.target.value)refreshDeliveryQuote(+e.target.value).catch(x=>{$('#order-form .form-error').textContent=x.message})});
