'use strict';
const config={apiUrl:localStorage.getItem('plated_api_url')||'http://localhost:8085',streamPath:localStorage.getItem('plated_stream_path')||'/payments/stream?orderId={id}',paths:{health:'/health',login:'/login',register:'/register',me:'/me',restaurants:'/restaurants',discover:(lat,lon)=>`/restaurants/discover?lat=${encodeURIComponent(lat)}&lon=${encodeURIComponent(lon)}`,orders:'/orders',tracking:id=>`/orders/${id}/tracking`,payments:'/payments',paymentForOrder:id=>`/payments/order/${id}`}};
const savedLocation=(()=>{try{return JSON.parse(localStorage.getItem('plated_location'))}catch{return null}})();
const state={token:localStorage.getItem('plated_token')||'',restaurants:[],orders:[],payments:new Map(),authMode:'login',watchers:new Map(),location:savedLocation,trackingTimer:null};
const $=(q,r=document)=>r.querySelector(q), $$=(q,r=document)=>[...r.querySelectorAll(q)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const distanceKm=(a,b)=>{const rad=x=>x*Math.PI/180,dLat=rad(b.latitude-a.latitude),dLon=rad(b.longitude-a.longitude),v=Math.sin(dLat/2)**2+Math.cos(rad(a.latitude))*Math.cos(rad(b.latitude))*Math.sin(dLon/2)**2;return 6371*2*Math.atan2(Math.sqrt(v),Math.sqrt(1-v))};
async function request(path,options={}){const headers={Accept:'application/json',...(options.body?{'Content-Type':'application/json'}:{}),...(options.headers||{})};if(state.token)headers.Authorization=`Bearer ${state.token}`;let response;try{response=await fetch(config.apiUrl+path,{...options,headers})}catch{throw new Error('Cannot reach the API gateway')};const text=await response.text();let data={};try{data=text?JSON.parse(text):{}}catch{data={message:text}}if(!response.ok)throw new Error(data.message||`Request failed (${response.status})`);return data}
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2800)}
function pending(button,on){button.disabled=on;button.dataset.label??=button.textContent;button.textContent=on?'Please wait…':button.dataset.label}
const emojis=['🥘','🍜','🍕','🥗','🍛','🌮'], colors=[['#f5a36f','#f7d87d'],['#81bd98','#dbe998'],['#a990c3','#edbdca'],['#6eb5c1','#b7ded8']];
function renderRestaurants(items=state.restaurants){const grid=$('#restaurant-grid');grid.ariaBusy='false';if(!items.length){grid.innerHTML='<div class="empty"><b>No restaurants found</b>Try another search, or refresh when restaurants have been added.</div>';return}grid.innerHTML=items.map((r,i)=>{const km=state.location?distanceKm(state.location,r):null,serviceable=km===null||km<=Number(r.deliveryRadiusKm||8);return `<article class="card"><div class="card-art" style="--a:${colors[i%4][0]};--b:${colors[i%4][1]}"><span>${emojis[i%6]}</span><span class="rating">★ ${Number(r.rating||0).toFixed(1)}</span></div><div class="card-body"><h3>${esc(r.name)}</h3><p>${esc(r.address||'Address coming soon')}<br>${esc(r.phone||'')}</p>${km===null?'':`<span class="distance ${serviceable?'':'out'}">${km.toFixed(1)} km · ${serviceable?'Delivers here':'Outside area'}</span>`}<button class="btn primary order-at" data-id="${Number(r.id)}" ${serviceable?'':'disabled'}>${serviceable?'Order here':'Unavailable'}</button></div></article>`}).join('');$$('.order-at:not([disabled])').forEach(b=>b.onclick=()=>openOrder(b.dataset.id))}
function renderOrders(){const box=$('#order-list');box.ariaBusy='false';if(!state.orders.length){box.innerHTML='<div class="empty"><b>No orders yet</b>Your first order will appear here.</div>';return}box.innerHTML=[...state.orders].reverse().map(o=>{const r=state.restaurants.find(x=>+x.id===+o.restaurantId),p=state.payments.get(+o.id),status=p?.status||o.status||'PENDING',normalized=String(status).toLowerCase(),payable=!['paid','success','succeeded','completed','failed','payment_failed','cancelled'].includes(normalized),trackable=Number(o.deliveryLatitude)!==0;return `<article class="order-row"><span class="order-icon">🥡</span><div><b>${esc(r?.name||`Restaurant #${o.restaurantId}`)}</b><small>Order #${o.id} · ${esc(o.deliveryAddress||'No delivery address')}</small></div><div class="order-side"><span class="badge ${esc(normalized)}">${esc(status)}</span> <b>₹${Number(o.totalAmount||0).toFixed(2)}</b><div>${trackable?`<button class="mini track" data-id="${o.id}">Track driver</button>`:''}${payable?`<button class="mini pay" data-id="${o.id}">Pay now</button>`:''}<button class="mini danger cancel" data-id="${o.id}">Cancel</button></div></div></article>`}).join('');$$('.track').forEach(b=>b.onclick=()=>openTracking(+b.dataset.id));$$('.pay').forEach(b=>b.onclick=()=>openPayment(+b.dataset.id));$$('.cancel').forEach(b=>b.onclick=()=>cancelOrder(+b.dataset.id))}
async function loadRestaurants(){const grid=$('#restaurant-grid');grid.ariaBusy='true';grid.innerHTML='<div class="skeleton"></div><div class="skeleton"></div><div class="skeleton"></div>';try{const data=await request(config.paths.restaurants);state.restaurants=Array.isArray(data)?data:[];$('#place-count').textContent=state.restaurants.length;renderRestaurants();fillRestaurants()}catch(e){grid.innerHTML=`<div class="error-box"><b>Restaurants are unavailable</b>${esc(e.message)}</div>`}}
async function loadPayment(orderId){try{const data=await request(config.paths.paymentForOrder(orderId));const payment=Array.isArray(data)?data.at(-1):data;if(payment?.status)state.payments.set(+orderId,payment)}catch{} }
async function loadOrders(){try{const data=await request(config.paths.orders);state.orders=Array.isArray(data)?data:[];await Promise.all(state.orders.map(o=>loadPayment(o.id)));renderOrders()}catch(e){$('#order-list').innerHTML=`<div class="error-box"><b>Orders are unavailable</b>${esc(e.message)}</div>`}}
async function health(){const el=$('#health');try{await request(config.paths.health);el.className='health online';el.innerHTML='<i></i><span>API online</span>'}catch{el.className='health offline';el.innerHTML='<i></i><span>API offline</span>'}}
function fillRestaurants(){const select=$('#order-form select');select.innerHTML='<option value="">Choose one</option>'+state.restaurants.map(r=>`<option value="${r.id}">${esc(r.name)}</option>`).join('')}
function openOrder(id=''){if(!state.token){toast('Sign in before placing an order');$('#auth-modal').showModal();return}if(!state.location){toast('Choose your delivery location first');$('.restaurants').scrollIntoView();return}fillRestaurants();$('#order-form').reset();$('#order-form').restaurantId.value=id;$('#order-form').deliveryAddress.value=localStorage.getItem('plated_address')||state.location.label||'';$('#order-form .form-error').textContent='';$('#order-modal').showModal()}
async function openTracking(id){clearTimeout(state.trackingTimer);$('#tracking-order').textContent=`#${id}`;$('#tracking-modal').showModal();const refresh=async()=>{try{const t=await request(config.paths.tracking(id));$('#driver-pin').style.left=`${15+Number(t.progressPercent)*.7}%`;$('#tracking-details').innerHTML=`<span><b>${esc(t.driverName)}</b>Driver #${t.driverId}</span><span><b>${t.etaMinutes} min</b>Estimated arrival</span><span><b>${t.progressPercent}%</b>${esc(t.status.replaceAll('_',' '))}</span>`;state.trackingTimer=setTimeout(refresh,5000)}catch(e){$('#tracking-details').innerHTML=`<div class="error-box"><b>Tracking unavailable</b>${esc(e.message)}</div>`}};refresh()}
async function openPayment(id){const o=state.orders.find(x=>+x.id===id);if(!o)return;const orderStatus=String(o.status||'').toLowerCase();if(['payment_failed','failed','cancelled'].includes(orderStatus)){toast('This order has no payable transaction. Create a new order with a valid amount.');return}const f=$('#payment-form');f.hidden=false;$('#payment-progress').hidden=true;f.reset();delete f.dataset.existingPayment;f.orderId.value=o.id;f.amount.value=o.totalAmount;$('#payment-order').textContent=`#${o.id}`;$('#payment-summary').innerHTML=`<b>Total due</b><span style="float:right;font-size:20px;font-weight:700">₹${Number(o.totalAmount).toFixed(2)}</span>`;$('#payment-modal').showModal();try{const data=await request(config.paths.paymentForOrder(o.id)),payment=Array.isArray(data)?data.at(-1):data;if(payment?.id||payment?.status){state.payments.set(+o.id,payment);f.dataset.existingPayment='true';f.hidden=true;$('#payment-progress').hidden=false;renderOrders();watchPayment(o.id)}else{$('.form-error',f).textContent='No payment exists for this order. Create a new order with a valid amount.'}}catch(e){$('.form-error',f).textContent=e.message} }
async function cancelOrder(id){if(!confirm(`Cancel order #${id}?`))return;try{await request(`${config.paths.orders}/${id}`,{method:'DELETE'});toast('Order cancelled');await loadOrders()}catch(e){toast(e.message)}}
function watchPayment(orderId){if(state.watchers.has(orderId))state.watchers.get(orderId)();let stopped=false,timer,stream;const update=p=>{if(!p?.status)return;state.payments.set(+orderId,p);renderOrders();const terminal=['paid','success','succeeded','completed','failed','cancelled'].includes(String(p.status).toLowerCase());if(terminal){toast(`Payment ${p.status}`);$('#payment-modal').close();stop()}};const handleEvent=e=>{try{update(JSON.parse(e.data))}catch{}};const poll=async()=>{if(stopped)return;try{const p=await request(config.paths.paymentForOrder(orderId));update(Array.isArray(p)?p.at(-1):p)}catch{}if(!stopped)timer=setTimeout(poll,2500)};try{const path=config.streamPath.replace('{id}',encodeURIComponent(orderId));stream=new EventSource(config.apiUrl+path);stream.onmessage=handleEvent;stream.addEventListener('payment-status',handleEvent);stream.onerror=()=>{stream.close();poll()}}catch{poll()}const stop=()=>{stopped=true;clearTimeout(timer);stream?.close();state.watchers.delete(orderId)};state.watchers.set(orderId,stop);setTimeout(()=>{if(!stopped)poll()},3000)}
$$('[data-close]').forEach(b=>b.onclick=()=>{if(b.closest('#tracking-modal'))clearTimeout(state.trackingTimer);b.closest('dialog').close()});$$('dialog').forEach(d=>d.onclick=e=>{if(e.target===d){if(d.id==='tracking-modal')clearTimeout(state.trackingTimer);d.close()}});
$('#auth-open').onclick=()=>{if(state.token){state.token='';localStorage.removeItem('plated_token');$('#auth-open').textContent='Sign in';toast('Signed out')}else $('#auth-modal').showModal()};
$$('[data-auth-mode]').forEach(b=>b.onclick=()=>{state.authMode=b.dataset.authMode;$$('[data-auth-mode]').forEach(x=>x.classList.toggle('active',x===b));$('.register-field').hidden=state.authMode==='login';$('.register-field input').required=state.authMode==='register';$('#auth-heading').textContent=state.authMode==='login'?'Sign in':'Create account'});
$('#auth-form').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,b=$('button[type="submit"]',f),body=Object.fromEntries(new FormData(f));if(state.authMode==='login')delete body.name;pending(b,true);try{const data=await request(config.paths[state.authMode],{method:'POST',body:JSON.stringify(body)});if(data.success===false)throw new Error(data.message);if(state.authMode==='register'){toast('Account created. Sign in now.');$('[data-auth-mode="login"]').click()}else{state.token=data.token;localStorage.setItem('plated_token',data.token);$('#auth-open').textContent='Sign out';$('#auth-modal').close();toast('Welcome back')}}catch(x){$('.form-error',f).textContent=x.message}finally{pending(b,false)}};
$('#order-form').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,b=$('button[type="submit"]',f),d=new FormData(f),body={restaurantId:+d.get('restaurantId'),totalAmount:+d.get('totalAmount'),deliveryLatitude:state.location.latitude,deliveryLongitude:state.location.longitude,deliveryAddress:d.get('deliveryAddress')};localStorage.setItem('plated_address',body.deliveryAddress);pending(b,true);try{await request(config.paths.orders,{method:'POST',body:JSON.stringify(body)});$('#order-modal').close();toast('Order placed and driver assigned');await loadOrders()}catch(x){$('.form-error',f).textContent=x.message}finally{pending(b,false)}};
$('#payment-form').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,b=$('button[type="submit"]',f),d=new FormData(f),key=crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`,body={orderId:+d.get('orderId'),amount:+d.get('amount'),paymentMethod:d.get('paymentMethod'),idempotencyKey:key};pending(b,true);try{let payment=state.payments.get(body.orderId);if(!payment){const result=await request(config.paths.payments,{method:'POST',headers:{'Idempotency-Key':key},body:JSON.stringify(body)});payment=result.payment||result}state.payments.set(body.orderId,payment);f.hidden=true;$('#payment-progress').hidden=false;watchPayment(body.orderId);renderOrders()}catch(x){$('.form-error',f).textContent=x.message}finally{pending(b,false)}};
$('#search').onsubmit=e=>{e.preventDefault();const q=$('#query').value.toLowerCase();renderRestaurants(state.restaurants.filter(r=>`${r.name} ${r.address}`.toLowerCase().includes(q)));$('.restaurants').scrollIntoView()};$('#query').oninput=e=>{if(!e.target.value)renderRestaurants()};$('#refresh').onclick=loadRestaurants;$('#reload-orders').onclick=loadOrders;$('#new-order').onclick=()=>openOrder();
function saveLocation(latitude,longitude,label){state.location={latitude,longitude,label};localStorage.setItem('plated_location',JSON.stringify(state.location));$('#location-status').textContent=`${label} · ${latitude.toFixed(5)}, ${longitude.toFixed(5)}`;renderRestaurants()}
async function discoverNearby(latitude,longitude){$('#location-status').textContent='Finding nearby restaurants…';try{const result=await request(config.paths.discover(latitude,longitude));state.location.label=result.city||state.location.label;localStorage.setItem('plated_location',JSON.stringify(state.location));await loadRestaurants();$('#location-status').textContent=`${state.location.label} · ${latitude.toFixed(5)}, ${longitude.toFixed(5)} · ${result.discovered} nearby`;toast(result.imported?`${result.imported} new restaurants imported`:`Nearby restaurants refreshed`)}catch(e){$('#location-status').textContent=`${state.location.label} · provider unavailable`;renderRestaurants();toast(e.message)}}
function selectAndDiscover(latitude,longitude,label){saveLocation(latitude,longitude,label);discoverNearby(latitude,longitude)}
$('#use-location').onclick=()=>{if(!navigator.geolocation){toast('Location is not supported by this browser');return}$('#location-status').textContent='Requesting browser location…';navigator.geolocation.getCurrentPosition(p=>selectAndDiscover(p.coords.latitude,p.coords.longitude,'Live GPS location'),e=>{$('#location-status').textContent='Location permission was not granted';toast(e.message)},{enableHighAccuracy:true,timeout:10000,maximumAge:30000})};
$('#demo-location').onclick=()=>selectAndDiscover(12.9716,77.5946,'Bengaluru test location');
$('#settings-open').onclick=()=>{const f=$('#settings-form');f.apiUrl.value=config.apiUrl;f.streamPath.value=config.streamPath;$('#settings-modal').showModal()};$('#settings-form').onsubmit=e=>{e.preventDefault();const d=new FormData(e.currentTarget);localStorage.setItem('plated_api_url',d.get('apiUrl').replace(/\/$/,''));localStorage.setItem('plated_stream_path',d.get('streamPath'));location.reload()};
if(state.token)$('#auth-open').textContent='Sign out';if(state.location)$('#location-status').textContent=`${state.location.label||'Saved location'} · ${Number(state.location.latitude).toFixed(5)}, ${Number(state.location.longitude).toFixed(5)}`;health();Promise.all([loadRestaurants(),loadOrders()]);
