'use strict';
const config={apiUrl:localStorage.getItem('plated_api_url')||'http://localhost:8085',streamPath:localStorage.getItem('plated_stream_path')||'/payments/stream?orderId={id}',paths:{health:'/health',login:'/login',register:'/register',me:'/me',restaurants:'/restaurants',discover:(lat,lon)=>`/restaurants/discover?lat=${encodeURIComponent(lat)}&lon=${encodeURIComponent(lon)}`,orders:'/orders',tracking:id=>`/orders/${id}/tracking`,payments:'/payments',paymentForOrder:id=>`/payments/order/${id}`,razorpayOrder:'/payments/razorpay/order',razorpayVerify:'/payments/razorpay/verify'}};
const savedLocation=(()=>{try{return JSON.parse(localStorage.getItem('plated_location'))}catch{return null}})();
const savedFavourites=(()=>{try{return JSON.parse(localStorage.getItem('plated_favourites'))||[]}catch{return []}})();
const state={token:localStorage.getItem('plated_token')||'',restaurants:[],orders:[],payments:new Map(),authMode:'login',watchers:new Map(),location:savedLocation,trackingTimer:null,discovering:false,cart:new Map(),coupon:'',profile:{},profileStorageKey:'',favourites:new Set(savedFavourites),favouritesOnly:false,ratingOnly:false,preselectedItem:''};
const $=(q,r=document)=>r.querySelector(q), $$=(q,r=document)=>[...r.querySelectorAll(q)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const checkoutState=id=>{try{return JSON.parse(localStorage.getItem(`plated_payment_${id}`)||'{}')}catch{return {}}};
const normalizedOrderStatus=value=>String(value??'').trim().toUpperCase();
const isDeliveredOrder=order=>normalizedOrderStatus(order?.status)==='DELIVERED';
const distanceKm=(a,b)=>{const rad=x=>x*Math.PI/180,dLat=rad(b.latitude-a.latitude),dLon=rad(b.longitude-a.longitude),v=Math.sin(dLat/2)**2+Math.cos(rad(a.latitude))*Math.cos(rad(b.latitude))*Math.sin(dLon/2)**2;return 6371*2*Math.atan2(Math.sqrt(v),Math.sqrt(1-v))};
async function request(path,options={}){const headers={Accept:'application/json',...(options.body?{'Content-Type':'application/json'}:{}),...(options.headers||{})};if(state.token)headers.Authorization=`Bearer ${state.token}`;let response;try{response=await fetch(config.apiUrl+path,{...options,headers})}catch{throw new Error('Cannot reach the API gateway')};const text=await response.text();let data={};try{data=text?JSON.parse(text):{}}catch{data={message:text}}if(!response.ok)throw new Error(data.message||`Request failed (${response.status})`);return data}
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2800)}
function pending(button,on){button.disabled=on;button.dataset.label??=button.textContent;button.textContent=on?'Please wait…':button.dataset.label}
const safeImageUrl=value=>{try{const url=new URL(value);return ['http:','https:'].includes(url.protocol)?url.href:''}catch{return ''}};
const testMenu=[{id:'biryani',name:'Chicken Biryani',description:'Basmati rice, chicken and aromatic spices',price:299,image:'assets/menu/chicken-biryani.png'},{id:'paneer',name:'Paneer Butter Masala',description:'Creamy tomato curry with naan',price:249,image:'assets/menu/paneer-butter-masala.png'},{id:'dosa',name:'Masala Dosa',description:'Crisp dosa, potato masala, sambar and chutney',price:179,image:'assets/menu/masala-dosa.png'}];
function renderRestaurants(items=state.restaurants){const grid=$('#restaurant-grid');grid.ariaBusy='false';if(state.favouritesOnly)items=items.filter(r=>state.favourites.has(Number(r.id)));if(state.ratingOnly)items=items.filter(r=>Number(r.rating)>=4.3);if(!items.length){grid.innerHTML=`<div class="empty"><b>${state.favouritesOnly?'No favourites yet':'No restaurants found'}</b>${state.favouritesOnly?'Tap a heart on any restaurant to save it.':'Try removing a filter or refreshing nearby places.'}</div>`;return}grid.innerHTML=items.map((r,i)=>{const km=state.location?distanceKm(state.location,r):null,serviceable=km===null||km<=Number(r.deliveryRadiusKm||8),providerPhoto=safeImageUrl(r.imageUrl),photo=providerPhoto||testMenu[i%testMenu.length].image,favourite=state.favourites.has(Number(r.id)),eta=km===null?25:Math.max(15,Math.round(14+km*3)),cuisine=['Biryani · North Indian','South Indian · Breakfast','North Indian · Vegetarian'][i%3];return `<article class="card"><div class="card-art has-photo"><img src="${esc(photo)}" alt="${providerPhoto?`${esc(r.name)} restaurant`:'Illustrative test menu food'}" loading="lazy"${providerPhoto?' referrerpolicy="no-referrer"':''}>${providerPhoto?'':'<span class="sample-photo">Sample menu photo</span>'}<span class="offer-badge">10% OFF</span><button class="favourite ${favourite?'active':''}" data-id="${Number(r.id)}" aria-label="${favourite?'Remove from':'Add to'} favourites">${favourite?'♥':'♡'}</button></div><div class="card-body"><div class="restaurant-title"><h3>${esc(r.name)}</h3><span class="score">${Number(r.rating||0).toFixed(1)} ★</span></div><p class="cuisine">${cuisine}</p><div class="restaurant-meta"><span>${km===null?'Nearby':`${km.toFixed(1)} km`}</span><span>•</span><b>${eta} min</b></div><p class="address-line">${esc(r.address||'Address coming soon')}</p><button class="btn primary order-at" data-id="${Number(r.id)}" ${serviceable?'':'disabled'}>${serviceable?'View menu':'Outside delivery area'}</button></div></article>`}).join('');$$('.favourite').forEach(button=>button.onclick=()=>{const id=Number(button.dataset.id);state.favourites.has(id)?state.favourites.delete(id):state.favourites.add(id);localStorage.setItem('plated_favourites',JSON.stringify([...state.favourites]));renderRestaurants();toast(state.favourites.has(id)?'Saved to favourites':'Removed from favourites')});$$('.order-at:not([disabled])').forEach(b=>b.onclick=()=>openOrder(b.dataset.id))}
function renderOrders(){const box=$('#order-list');box.ariaBusy='false';if(!state.orders.length){box.innerHTML='<div class="empty"><b>No orders yet</b>Your first order will appear here.</div>';return}box.innerHTML=[...state.orders].reverse().map(o=>{const r=state.restaurants.find(x=>+x.id===+o.restaurantId),p=state.payments.get(+o.id),ui=checkoutState(o.id),orderStatus=normalizedOrderStatus(o.status),deliveryStates=['ASSIGNED','PICKED_UP','ON_THE_WAY','ARRIVING','DELIVERED'],delivered=isDeliveredOrder(o),paid=['paid','success','succeeded','completed'].includes(String(p?.status).trim().toLowerCase()),deliveryActive=deliveryStates.includes(orderStatus),status=deliveryActive?orderStatus:paid?'PAID · PREPARING':ui.status==='in_progress'?'PAYMENT_IN_PROGRESS':ui.status==='failed'?'PAYMENT_RETRY_NEEDED':p?.status||orderStatus||'PENDING',normalized=String(status).toLowerCase().replaceAll(' · ','_').replaceAll(' ','_'),payable=!paid&&!deliveryActive&&!['CANCELLED','PAYMENT_FAILED'].includes(orderStatus),trackable=!delivered&&paid&&Number(o.deliveryLatitude)!==0,cancellable=!delivered;return `<article class="order-row ${ui.status==='in_progress'?'payment-active':''}"><span class="order-icon">${paid?'✓':'🥡'}</span><div><b>${esc(r?.name||`Restaurant #${o.restaurantId}`)}</b><small>${esc(o.itemSummary||'Legacy order')}<br>Order #${o.id} · ${esc(o.deliveryAddress||'No delivery address')}</small></div><div class="order-side"><span class="badge ${esc(normalized)}">${esc(String(status).replaceAll('_',' '))}</span> <b>₹${Number(o.totalAmount||0).toFixed(2)}</b><div>${trackable?`<button class="mini track" data-id="${o.id}">Track driver</button>`:''}${payable?`<button class="mini pay" data-id="${o.id}">${ui.status==='in_progress'?'Open payment':'Pay now'}</button>`:''}${cancellable?`<button class="mini danger cancel" data-id="${o.id}">Cancel</button>`:''}</div></div></article>`}).join('');$$('.track').forEach(b=>b.onclick=()=>openTracking(+b.dataset.id));$$('.pay').forEach(b=>b.onclick=()=>openPayment(+b.dataset.id));$$('.cancel').forEach(b=>b.onclick=()=>cancelOrder(+b.dataset.id))}
async function loadRestaurants(){const grid=$('#restaurant-grid');grid.ariaBusy='true';grid.innerHTML='<div class="skeleton"></div><div class="skeleton"></div><div class="skeleton"></div>';try{const data=await request(config.paths.restaurants);state.restaurants=Array.isArray(data)?data:[];$('#place-count').textContent=state.restaurants.length;renderRestaurants();fillRestaurants()}catch(e){grid.innerHTML=`<div class="error-box"><b>Restaurants are unavailable</b>${esc(e.message)}</div>`}}
async function loadPayment(orderId){try{const data=await request(config.paths.paymentForOrder(orderId));const payment=Array.isArray(data)?data.at(-1):data;if(payment?.status)state.payments.set(+orderId,payment)}catch{} }
async function loadPaymentsBounded(orders,concurrency=8){let next=0;const worker=async()=>{while(next<orders.length){const order=orders[next++];await loadPayment(order.id)}};await Promise.all(Array.from({length:Math.min(concurrency,orders.length)},worker))}
async function loadOrders(){try{const data=await request(config.paths.orders);state.orders=Array.isArray(data)?data:[];await loadPaymentsBounded(state.orders);renderOrders()}catch(e){$('#order-list').innerHTML=`<div class="error-box"><b>Orders are unavailable</b>${esc(e.message)}</div>`}}
async function health(){const el=$('#health');try{await request(config.paths.health);el.className='health online';el.innerHTML='<i></i><span>API online</span>'}catch{el.className='health offline';el.innerHTML='<i></i><span>API offline</span>'}}
function fillRestaurants(){const select=$('#order-form select');select.innerHTML='<option value="">Choose one</option>'+state.restaurants.map(r=>`<option value="${r.id}">${esc(r.name)}</option>`).join('')}
function priceOrder(){const subtotal=testMenu.reduce((sum,item)=>sum+(state.cart.get(item.id)||0)*item.price,0),discount=state.coupon==='WELCOME10'?Math.min(subtotal*.1,100):0,deliveryFee=subtotal===0?0:Number(state.deliveryQuote?.deliveryFee??39),total=subtotal-discount+deliveryFee;return{subtotal,discount,deliveryFee,total}}
function renderMenu(){const box=$('#menu-items');box.innerHTML=testMenu.map(item=>{const qty=state.cart.get(item.id)||0;return `<article class="menu-item"><img src="${item.image}" alt="${esc(item.name)} test menu photo"><div><b>${esc(item.name)}</b><small>${esc(item.description)} · ₹${item.price.toFixed(2)}</small></div><div class="qty"><button type="button" data-item="${item.id}" data-delta="-1" aria-label="Remove one ${esc(item.name)}">−</button><b>${qty}</b><button type="button" data-item="${item.id}" data-delta="1" aria-label="Add one ${esc(item.name)}">+</button></div></article>`}).join('');$$('.qty button',box).forEach(button=>button.onclick=()=>{const id=button.dataset.item,next=Math.max(0,(state.cart.get(id)||0)+Number(button.dataset.delta));state.cart.set(id,next);renderMenu();renderPrice()})}
function renderPrice(){const p=priceOrder(),q=state.deliveryQuote;$('#price-breakdown').innerHTML=`<div class="price-line"><span>Subtotal</span><b>₹${p.subtotal.toFixed(2)}</b></div><div class="price-line"><span>Test discount${state.coupon?' (WELCOME10)':''}</span><b>−₹${p.discount.toFixed(2)}</b></div><div class="price-line"><span>Delivery fee${q?` · ${Number(q.distanceKm).toFixed(1)} km`:''}</span><b>₹${p.deliveryFee.toFixed(2)}</b></div>${q?`<div class="price-line"><span>Estimated delivery</span><b>${q.etaMinutes} min</b></div><small class="hint">${q.zoneType} zone${q.rules?.rain?' · rain pricing':''}${q.rules?.surge?' · surge pricing':''}${q.rules?.lateNight?' · late-night pricing':''}</small>`:''}<div class="price-line total"><span>Total</span><b>₹${p.total.toFixed(2)}</b></div>`}
function renderCheckoutAddress(){const address=state.selectedAddress,label=$('#checkout-address-label'),text=$('#checkout-address-text');if(!label||!text)return;label.textContent=address?`${address.label} · ${address.recipient}`:'Saved delivery point';text.textContent=address?`${address.addressLine}${address.deliveryNotes?` · ${address.deliveryNotes}`:''}`:(state.location?.label||'Choose a saved delivery address')}
function openOrder(id=''){if(!state.token){toast('Sign in before placing an order');$('#auth-modal').showModal();return}if(!state.selectedAddress){toast('Choose or add a saved delivery address first');$('#manage-addresses').click();return}fillRestaurants();$('#order-form').reset();state.cart=new Map();if(state.preselectedItem)state.cart.set(state.preselectedItem,1);state.coupon='';state.deliveryQuote=null;$('#order-form').restaurantId.value=id;renderCheckoutAddress();$('#order-form .form-error').textContent='';renderMenu();renderPrice();$('#order-modal').showModal();if(id)refreshDeliveryQuote(+id);state.preselectedItem=''}
async function openTracking(id){const selected=state.orders.find(order=>+order.id===id);if(isDeliveredOrder(selected)){toast(`Order #${id} is already delivered`);await loadOrders();return}clearTimeout(state.trackingTimer);$('#tracking-order').textContent=`#${id}`;$('#tracking-modal').showModal();const refresh=async()=>{try{const t=await request(config.paths.tracking(id)),trackingStatus=normalizedOrderStatus(t.status),delivered=trackingStatus==='DELIVERED';$('#driver-pin').style.left=`${15+Number(t.progressPercent)*.7}%`;$('#driver-profile').innerHTML=`<div><b>${esc(t.driverName)} ${t.live?'· Live GPS':'· Location stale'}</b><small>${esc(t.driverContact)} · accuracy ±${Math.round(Number(t.accuracyMeters||0))} m</small></div><div><b>${esc(t.vehicleType)}</b><small>${esc(t.vehiclePlate)}</small></div>`;$('#tracking-details').innerHTML=`<span><b>${delivered?'Delivered':`${t.etaMinutes} min`}</b>${delivered?'Reached your location':'Estimated arrival'}</span><span><b>${t.progressPercent}%</b>${esc(trackingStatus.replaceAll('_',' '))}</span><span><b>${t.locationAgeSeconds}s ago</b>${t.live?'Live GPS update':'Waiting for a fresh GPS fix'}</span>`;$('#delivery-timeline').innerHTML=(t.timeline||[]).map(s=>`<span class="delivery-step ${s.complete?'complete':''}">${esc(normalizedOrderStatus(s.status).replaceAll('_',' '))}</span>`).join('');if(delivered){clearTimeout(state.trackingTimer);await loadOrders();$('#tracking-modal').close();toast(`Order #${id} delivered`);return}}catch(e){$('#driver-profile').textContent='Waiting for driver GPS…';$('#tracking-details').innerHTML=`<div class="error-box"><b>Live location unavailable</b>${esc(e.message)}</div>`}state.trackingTimer=setTimeout(refresh,5000)};refresh()}
function openPayment(id){const o=state.orders.find(x=>+x.id===id);if(!o)return;if(String(o.status).toLowerCase()==='cancelled'){toast('Cancelled orders cannot be paid');return}localStorage.setItem(`plated_payment_${id}`,JSON.stringify({status:'in_progress',updatedAt:Date.now()}));renderOrders();const page=`payment.html?orderId=${encodeURIComponent(id)}`;const popup=window.open(page,`plated-payment-${id}`);if(!popup)window.location.href=page}
async function cancelOrder(id){if(!confirm(`Cancel order #${id}?`))return;try{await request(`${config.paths.orders}/${id}`,{method:'DELETE'});toast('Order cancelled');await loadOrders()}catch(e){toast(e.message)}}
function paintAvatar(element){const name=state.profile.name||state.profile.email||'Profile',initial=name.trim().charAt(0).toUpperCase()||'P';element.textContent=initial;element.style.backgroundImage=state.profile.photo?`url("${state.profile.photo}")`:'';element.classList.toggle('has-image',Boolean(state.profile.photo))}
function updateProfileUI(){const button=$('#profile-open');button.hidden=!state.token;if(!state.token)return;paintAvatar($('#profile-avatar-small'));paintAvatar($('#profile-avatar-large'));$('#profile-label').textContent=(state.profile.name||'Profile').split(' ')[0];const f=$('#profile-form');f.name.value=state.profile.name||'';f.email.value=state.profile.email||'';f.phone.value=state.profile.phone||'';f.upiId.value=state.profile.upiId||''}
async function loadIdentity(){if(!state.token)return;try{const me=await request(config.paths.me);state.profileStorageKey=`plated_profile_user_${Number(me.id)}`;let saved={};try{saved=JSON.parse(localStorage.getItem(state.profileStorageKey)||'{}')}catch{}state.profile={...saved,name:saved.name||me.name||'',email:me.email||''};localStorage.setItem(state.profileStorageKey,JSON.stringify(state.profile));updateProfileUI()}catch{}}
function resizeProfilePhoto(file){return new Promise((resolve,reject)=>{if(!file.type.startsWith('image/'))return reject(new Error('Choose a PNG, JPEG, or WebP image'));if(file.size>5*1024*1024)return reject(new Error('Profile photo must be smaller than 5 MB'));const reader=new FileReader();reader.onerror=()=>reject(new Error('Could not read profile photo'));reader.onload=()=>{const img=new Image();img.onerror=()=>reject(new Error('Could not open profile photo'));img.onload=()=>{const canvas=document.createElement('canvas');canvas.width=256;canvas.height=256;const ctx=canvas.getContext('2d'),side=Math.min(img.width,img.height),sx=(img.width-side)/2,sy=(img.height-side)/2;ctx.drawImage(img,sx,sy,side,side,0,0,256,256);resolve(canvas.toDataURL('image/jpeg',.82))};img.src=reader.result};reader.readAsDataURL(file)})}
$$('[data-close]').forEach(b=>b.onclick=()=>{if(b.closest('#tracking-modal'))clearTimeout(state.trackingTimer);b.closest('dialog').close()});$$('dialog').forEach(d=>d.onclick=e=>{if(e.target===d){if(d.id==='tracking-modal')clearTimeout(state.trackingTimer);d.close()}});
$('#auth-open').onclick=()=>{if(state.token){state.token='';state.profile={};state.profileStorageKey='';localStorage.removeItem('plated_token');$('#auth-open').textContent='Sign in';updateProfileUI();toast('Signed out')}else $('#auth-modal').showModal()};
$('#profile-open').onclick=()=>{updateProfileUI();$('#profile-form .form-error').textContent='';$('#profile-modal').showModal()};
$('#profile-addresses').onclick=()=>{$('#profile-modal').close();$('#manage-addresses').click()};
$('#orders-open').onclick=()=>{if(!state.token){toast('Sign in to view your orders');$('#auth-modal').showModal();return}loadOrders();$('#orders-modal').showModal()};
$('#service-orders').onclick=()=>$('#orders-open').click();
$('#service-start-order').onclick=()=>openOrder();
$('#checkout-change-address').onclick=()=>{state.returnToOrderAfterAddress=true;$('#order-modal').close();$('#manage-addresses').click()};
$('#profile-form').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,b=$('button[type="submit"]',f),d=new FormData(f),upiId=String(d.get('upiId')||'').trim();if(!state.profileStorageKey){$('.form-error',f).textContent='Sign in again before saving your profile';return}if(upiId&&!/^[a-zA-Z0-9._-]{2,}@[a-zA-Z]{2,}$/.test(upiId)){$('.form-error',f).textContent='Enter a valid test UPI ID such as name@bank';return}pending(b,true);try{const file=f.photo.files[0],photo=file?await resizeProfilePhoto(file):state.profile.photo||'';state.profile={...state.profile,name:String(d.get('name')).trim(),email:String(d.get('email')).trim(),phone:String(d.get('phone')).trim(),upiId,photo};localStorage.setItem(state.profileStorageKey,JSON.stringify(state.profile));updateProfileUI();$('#profile-modal').close();toast('Profile saved only for this signed-in account')}catch(x){$('.form-error',f).textContent=x.message}finally{pending(b,false)}};
$$('[data-auth-mode]').forEach(b=>b.onclick=()=>{state.authMode=b.dataset.authMode;$$('[data-auth-mode]').forEach(x=>x.classList.toggle('active',x===b));$('.register-field').hidden=state.authMode==='login';$('.register-field input').required=state.authMode==='register';$('#auth-heading').textContent=state.authMode==='login'?'Sign in':'Create account'});
$('#auth-form').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,b=$('button[type="submit"]',f),body=Object.fromEntries(new FormData(f));body.email=String(body.email||'').trim().toLowerCase();if(state.authMode==='login')delete body.name;else if(!/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[^A-Za-z0-9]).{10,128}$/.test(String(body.password||''))){$('.form-error',f).textContent='Use 10+ characters with uppercase, lowercase, a number, and a symbol';return}pending(b,true);try{const data=await request(config.paths[state.authMode],{method:'POST',body:JSON.stringify(body)});if(data.success===false)throw new Error(data.message);if(state.authMode==='register'){toast('Account created. Sign in now.');$('[data-auth-mode="login"]').click()}else{state.token=data.token;state.profile={};state.profileStorageKey='';localStorage.setItem('plated_token',data.token);$('#auth-open').textContent='Sign out';$('#auth-modal').close();await loadIdentity();await loadAddresses();toast('Welcome back')}}catch(x){$('.form-error',f).textContent=x.message}finally{pending(b,false)}};
$('#apply-coupon').onclick=()=>{const value=$('#order-form').coupon.value.trim().toUpperCase();state.coupon=value==='WELCOME10'?value:'';toast(state.coupon?'WELCOME10 applied':'Use test code WELCOME10');renderPrice()};
$('#order-form').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,b=$('button[type="submit"]',f),d=new FormData(f),selected=testMenu.filter(item=>(state.cart.get(item.id)||0)>0);if(!state.selectedAddress){$('.form-error',f).textContent='Choose a saved delivery address';return}if(!selected.length){$('.form-error',f).textContent='Add at least one food item';return}try{await refreshDeliveryQuote(+d.get('restaurantId'))}catch(x){$('.form-error',f).textContent=x.message;return}const pricing=priceOrder(),body={restaurantId:+d.get('restaurantId'),addressId:state.selectedAddress.id,totalAmount:+pricing.total,subtotal:+pricing.subtotal,discountAmount:+pricing.discount,deliveryFee:+pricing.deliveryFee,itemSummary:selected.map(item=>`${item.name} × ${state.cart.get(item.id)}`).join(', '),deliveryLatitude:state.location.latitude,deliveryLongitude:state.location.longitude,deliveryAddress:state.selectedAddress.addressLine};pending(b,true);try{const created=await request(config.paths.orders,{method:'POST',body:JSON.stringify(body)});if(!created.orderId)throw new Error('Order was created without a checkout reference');$('#order-modal').close();toast('Order placed · opening secure test payment');await loadOrders();window.location.assign(`payment.html?orderId=${encodeURIComponent(created.orderId)}`)}catch(x){$('.form-error',f).textContent=x.message}finally{pending(b,false)}};
$('#search').onsubmit=e=>{e.preventDefault();const q=$('#query').value.toLowerCase();renderRestaurants(state.restaurants.filter(r=>`${r.name} ${r.address}`.toLowerCase().includes(q)));$('.restaurants').scrollIntoView()};$('#query').oninput=e=>{if(!e.target.value)renderRestaurants()};$$('.category-card').forEach(button=>button.onclick=()=>{state.preselectedItem=button.dataset.menuItem;toast(`${testMenu.find(item=>item.id===state.preselectedItem)?.name} selected — choose a restaurant`);$('.restaurants').scrollIntoView()});$('#browse-offer').onclick=()=>{$('.restaurants').scrollIntoView();toast('Use WELCOME10 during checkout')};$('#rating-filter').onclick=()=>{state.ratingOnly=!state.ratingOnly;$('#rating-filter').classList.toggle('active',state.ratingOnly);renderRestaurants()};$('#show-favourites').onclick=()=>{state.favouritesOnly=!state.favouritesOnly;$('#show-favourites').textContent=state.favouritesOnly?'Show all':'♡ Favourites';$('#show-favourites').classList.toggle('active',state.favouritesOnly);renderRestaurants()};$('#refresh').onclick=loadRestaurants;$('#reload-orders').onclick=loadOrders;$('#new-order').onclick=()=>openOrder();
function saveLocation(latitude,longitude,label){state.location={latitude,longitude,label};localStorage.setItem('plated_location',JSON.stringify(state.location));$('#location-status').textContent=`${label} · ${latitude.toFixed(5)}, ${longitude.toFixed(5)}`;renderRestaurants()}
async function discoverNearby(latitude,longitude){if(state.discovering)return;state.discovering=true;const buttons=[$('#use-location'),$('#demo-location')];buttons.forEach(b=>b.disabled=true);$('#location-status').textContent='Finding nearby restaurants…';try{const result=await request(config.paths.discover(latitude,longitude));state.location.label=result.city||state.location.label;localStorage.setItem('plated_location',JSON.stringify(state.location));await loadRestaurants();$('#location-status').textContent=`${state.location.label} · ${latitude.toFixed(5)}, ${longitude.toFixed(5)} · ${result.discovered} nearby`;toast(result.imported?`${result.imported} new restaurants imported`:`Nearby restaurants refreshed`)}catch(e){await loadRestaurants();$('#location-status').textContent=`${state.location.label} · provider unavailable · showing saved restaurants`;toast('Live discovery is busy; saved restaurants are shown. Try again shortly.')}finally{state.discovering=false;buttons.forEach(b=>b.disabled=false)}}
function selectAndDiscover(latitude,longitude,label){saveLocation(latitude,longitude,label);discoverNearby(latitude,longitude)}
$('#use-location').onclick=()=>{if(!navigator.geolocation){toast('Location is not supported by this browser');return}$('#location-status').textContent='Requesting browser location…';navigator.geolocation.getCurrentPosition(p=>selectAndDiscover(p.coords.latitude,p.coords.longitude,'Live GPS location'),e=>{$('#location-status').textContent='Location permission was not granted';toast(e.message)},{enableHighAccuracy:true,timeout:10000,maximumAge:30000})};
$('#demo-location').onclick=()=>selectAndDiscover(12.9716,77.5946,'Bengaluru test location');
$('#settings-open').onclick=()=>{const f=$('#settings-form');f.apiUrl.value=config.apiUrl;f.streamPath.value=config.streamPath;$('#settings-modal').showModal()};$('#settings-form').onsubmit=e=>{e.preventDefault();const d=new FormData(e.currentTarget);localStorage.setItem('plated_api_url',d.get('apiUrl').replace(/\/$/,''));localStorage.setItem('plated_stream_path',d.get('streamPath'));location.reload()};
window.addEventListener('storage',event=>{if(event.key?.startsWith('plated_payment_'))loadOrders()});window.addEventListener('focus',()=>{if(state.token)loadOrders()});
if(state.token)$('#auth-open').textContent='Sign out';updateProfileUI();if(state.token)loadIdentity();if(state.location)$('#location-status').textContent=`${state.location.label||'Saved location'} · ${Number(state.location.latitude).toFixed(5)}, ${Number(state.location.longitude).toFixed(5)}`;health();Promise.all([loadRestaurants(),loadOrders()]).then(()=>{if(new URLSearchParams(location.search).get('view')==='orders'&&state.token)$('#orders-modal').showModal()});
