'use strict';
const config={apiUrl:localStorage.getItem('plated_api_url')||'http://localhost:8085',streamPath:localStorage.getItem('plated_stream_path')||'/payments/stream?orderId={id}',paths:{health:'/health',login:'/login',register:'/register',me:'/me',restaurants:'/restaurants',discover:(lat,lon)=>`/restaurants/discover?lat=${encodeURIComponent(lat)}&lon=${encodeURIComponent(lon)}`,orders:'/orders',tracking:id=>`/orders/${id}/tracking`,payments:'/payments',paymentForOrder:id=>`/payments/order/${id}`}};
const savedLocation=(()=>{try{return JSON.parse(localStorage.getItem('plated_location'))}catch{return null}})();
const savedProfile=(()=>{try{return JSON.parse(localStorage.getItem('plated_profile'))||{}}catch{return {}}})();
const savedFavourites=(()=>{try{return JSON.parse(localStorage.getItem('plated_favourites'))||[]}catch{return []}})();
const state={token:localStorage.getItem('plated_token')||'',restaurants:[],orders:[],payments:new Map(),authMode:'login',watchers:new Map(),location:savedLocation,trackingTimer:null,discovering:false,cart:new Map(),coupon:'',profile:savedProfile,favourites:new Set(savedFavourites),favouritesOnly:false,ratingOnly:false,preselectedItem:''};
const $=(q,r=document)=>r.querySelector(q), $$=(q,r=document)=>[...r.querySelectorAll(q)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const distanceKm=(a,b)=>{const rad=x=>x*Math.PI/180,dLat=rad(b.latitude-a.latitude),dLon=rad(b.longitude-a.longitude),v=Math.sin(dLat/2)**2+Math.cos(rad(a.latitude))*Math.cos(rad(b.latitude))*Math.sin(dLon/2)**2;return 6371*2*Math.atan2(Math.sqrt(v),Math.sqrt(1-v))};
async function request(path,options={}){const headers={Accept:'application/json',...(options.body?{'Content-Type':'application/json'}:{}),...(options.headers||{})};if(state.token)headers.Authorization=`Bearer ${state.token}`;let response;try{response=await fetch(config.apiUrl+path,{...options,headers})}catch{throw new Error('Cannot reach the API gateway')};const text=await response.text();let data={};try{data=text?JSON.parse(text):{}}catch{data={message:text}}if(!response.ok)throw new Error(data.message||`Request failed (${response.status})`);return data}
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2800)}
function pending(button,on){button.disabled=on;button.dataset.label??=button.textContent;button.textContent=on?'Please wait…':button.dataset.label}
const safeImageUrl=value=>{try{const url=new URL(value);return ['http:','https:'].includes(url.protocol)?url.href:''}catch{return ''}};
const testMenu=[{id:'biryani',name:'Chicken Biryani',description:'Basmati rice, chicken and aromatic spices',price:299,image:'assets/menu/chicken-biryani.png'},{id:'paneer',name:'Paneer Butter Masala',description:'Creamy tomato curry with naan',price:249,image:'assets/menu/paneer-butter-masala.png'},{id:'dosa',name:'Masala Dosa',description:'Crisp dosa, potato masala, sambar and chutney',price:179,image:'assets/menu/masala-dosa.png'}];
function renderRestaurants(items=state.restaurants){const grid=$('#restaurant-grid');grid.ariaBusy='false';if(state.favouritesOnly)items=items.filter(r=>state.favourites.has(Number(r.id)));if(state.ratingOnly)items=items.filter(r=>Number(r.rating)>=4.3);if(!items.length){grid.innerHTML=`<div class="empty"><b>${state.favouritesOnly?'No favourites yet':'No restaurants found'}</b>${state.favouritesOnly?'Tap a heart on any restaurant to save it.':'Try removing a filter or refreshing nearby places.'}</div>`;return}grid.innerHTML=items.map((r,i)=>{const km=state.location?distanceKm(state.location,r):null,serviceable=km===null||km<=Number(r.deliveryRadiusKm||8),providerPhoto=safeImageUrl(r.imageUrl),photo=providerPhoto||testMenu[i%testMenu.length].image,favourite=state.favourites.has(Number(r.id)),eta=km===null?25:Math.max(15,Math.round(14+km*3)),cuisine=['Biryani · North Indian','South Indian · Breakfast','North Indian · Vegetarian'][i%3];return `<article class="card"><div class="card-art has-photo"><img src="${esc(photo)}" alt="${providerPhoto?`${esc(r.name)} restaurant`:'Illustrative test menu food'}" loading="lazy"${providerPhoto?' referrerpolicy="no-referrer"':''}>${providerPhoto?'':'<span class="sample-photo">Sample menu photo</span>'}<span class="offer-badge">10% OFF</span><button class="favourite ${favourite?'active':''}" data-id="${Number(r.id)}" aria-label="${favourite?'Remove from':'Add to'} favourites">${favourite?'♥':'♡'}</button></div><div class="card-body"><div class="restaurant-title"><h3>${esc(r.name)}</h3><span class="score">${Number(r.rating||0).toFixed(1)} ★</span></div><p class="cuisine">${cuisine}</p><div class="restaurant-meta"><span>${km===null?'Nearby':`${km.toFixed(1)} km`}</span><span>•</span><b>${eta} min</b></div><p class="address-line">${esc(r.address||'Address coming soon')}</p><button class="btn primary order-at" data-id="${Number(r.id)}" ${serviceable?'':'disabled'}>${serviceable?'View menu':'Outside delivery area'}</button></div></article>`}).join('');$$('.favourite').forEach(button=>button.onclick=()=>{const id=Number(button.dataset.id);state.favourites.has(id)?state.favourites.delete(id):state.favourites.add(id);localStorage.setItem('plated_favourites',JSON.stringify([...state.favourites]));renderRestaurants();toast(state.favourites.has(id)?'Saved to favourites':'Removed from favourites')});$$('.order-at:not([disabled])').forEach(b=>b.onclick=()=>openOrder(b.dataset.id))}
function renderOrders(){const box=$('#order-list');box.ariaBusy='false';if(!state.orders.length){box.innerHTML='<div class="empty"><b>No orders yet</b>Your first order will appear here.</div>';return}box.innerHTML=[...state.orders].reverse().map(o=>{const r=state.restaurants.find(x=>+x.id===+o.restaurantId),p=state.payments.get(+o.id),deliveryStates=['ASSIGNED','PICKED_UP','ON_THE_WAY','ARRIVING','DELIVERED'],status=deliveryStates.includes(o.status)?o.status:p?.status||o.status||'PENDING',normalized=String(status).toLowerCase(),payable=!['paid','success','succeeded','completed','delivered','failed','payment_failed','cancelled'].includes(normalized),trackable=Number(o.deliveryLatitude)!==0;return `<article class="order-row"><span class="order-icon">🥡</span><div><b>${esc(r?.name||`Restaurant #${o.restaurantId}`)}</b><small>${esc(o.itemSummary||'Legacy order')}<br>Order #${o.id} · ${esc(o.deliveryAddress||'No delivery address')}</small></div><div class="order-side"><span class="badge ${esc(normalized)}">${esc(status.replaceAll('_',' '))}</span> <b>₹${Number(o.totalAmount||0).toFixed(2)}</b><div>${trackable?`<button class="mini track" data-id="${o.id}">Track driver</button>`:''}${payable?`<button class="mini pay" data-id="${o.id}">Pay now</button>`:''}<button class="mini danger cancel" data-id="${o.id}">Cancel</button></div></div></article>`}).join('');$$('.track').forEach(b=>b.onclick=()=>openTracking(+b.dataset.id));$$('.pay').forEach(b=>b.onclick=()=>openPayment(+b.dataset.id));$$('.cancel').forEach(b=>b.onclick=()=>cancelOrder(+b.dataset.id))}
async function loadRestaurants(){const grid=$('#restaurant-grid');grid.ariaBusy='true';grid.innerHTML='<div class="skeleton"></div><div class="skeleton"></div><div class="skeleton"></div>';try{const data=await request(config.paths.restaurants);state.restaurants=Array.isArray(data)?data:[];$('#place-count').textContent=state.restaurants.length;renderRestaurants();fillRestaurants()}catch(e){grid.innerHTML=`<div class="error-box"><b>Restaurants are unavailable</b>${esc(e.message)}</div>`}}
async function loadPayment(orderId){try{const data=await request(config.paths.paymentForOrder(orderId));const payment=Array.isArray(data)?data.at(-1):data;if(payment?.status)state.payments.set(+orderId,payment)}catch{} }
async function loadOrders(){try{const data=await request(config.paths.orders);state.orders=Array.isArray(data)?data:[];await Promise.all(state.orders.map(o=>loadPayment(o.id)));renderOrders()}catch(e){$('#order-list').innerHTML=`<div class="error-box"><b>Orders are unavailable</b>${esc(e.message)}</div>`}}
async function health(){const el=$('#health');try{await request(config.paths.health);el.className='health online';el.innerHTML='<i></i><span>API online</span>'}catch{el.className='health offline';el.innerHTML='<i></i><span>API offline</span>'}}
function fillRestaurants(){const select=$('#order-form select');select.innerHTML='<option value="">Choose one</option>'+state.restaurants.map(r=>`<option value="${r.id}">${esc(r.name)}</option>`).join('')}
function priceOrder(){const subtotal=testMenu.reduce((sum,item)=>sum+(state.cart.get(item.id)||0)*item.price,0),discount=state.coupon==='WELCOME10'?Math.min(subtotal*.1,100):0,deliveryFee=subtotal>=499||subtotal===0?0:39,total=subtotal-discount+deliveryFee;return{subtotal,discount,deliveryFee,total}}
function renderMenu(){const box=$('#menu-items');box.innerHTML=testMenu.map(item=>{const qty=state.cart.get(item.id)||0;return `<article class="menu-item"><img src="${item.image}" alt="${esc(item.name)} test menu photo"><div><b>${esc(item.name)}</b><small>${esc(item.description)} · ₹${item.price.toFixed(2)}</small></div><div class="qty"><button type="button" data-item="${item.id}" data-delta="-1" aria-label="Remove one ${esc(item.name)}">−</button><b>${qty}</b><button type="button" data-item="${item.id}" data-delta="1" aria-label="Add one ${esc(item.name)}">+</button></div></article>`}).join('');$$('.qty button',box).forEach(button=>button.onclick=()=>{const id=button.dataset.item,next=Math.max(0,(state.cart.get(id)||0)+Number(button.dataset.delta));state.cart.set(id,next);renderMenu();renderPrice()})}
function renderPrice(){const p=priceOrder();$('#price-breakdown').innerHTML=`<div class="price-line"><span>Subtotal</span><b>₹${p.subtotal.toFixed(2)}</b></div><div class="price-line"><span>Test discount${state.coupon?' (WELCOME10)':''}</span><b>−₹${p.discount.toFixed(2)}</b></div><div class="price-line"><span>Delivery fee</span><b>₹${p.deliveryFee.toFixed(2)}</b></div><div class="price-line total"><span>Total</span><b>₹${p.total.toFixed(2)}</b></div>`}
function openOrder(id=''){if(!state.token){toast('Sign in before placing an order');$('#auth-modal').showModal();return}if(!state.location){toast('Choose your delivery location first');$('.restaurants').scrollIntoView();return}fillRestaurants();$('#order-form').reset();state.cart=new Map();if(state.preselectedItem)state.cart.set(state.preselectedItem,1);state.coupon='';$('#order-form').restaurantId.value=id;$('#order-form').deliveryAddress.value=localStorage.getItem('plated_address')||state.location.label||'';$('#order-form .form-error').textContent='';renderMenu();renderPrice();$('#order-modal').showModal();state.preselectedItem=''}
async function openTracking(id){clearTimeout(state.trackingTimer);$('#tracking-order').textContent=`#${id}`;$('#tracking-modal').showModal();const refresh=async()=>{try{const t=await request(config.paths.tracking(id));$('#driver-pin').style.left=`${15+Number(t.progressPercent)*.7}%`;$('#driver-profile').innerHTML=`<div><b>${esc(t.driverName)} · ★ ${Number(t.driverRating).toFixed(1)}</b><small>${esc(t.driverContact)} (test contact)</small></div><div><b>${esc(t.vehicleType)}</b><small>${esc(t.vehiclePlate)}</small></div>`;$('#tracking-details').innerHTML=`<span><b>${t.status==='DELIVERED'?'Delivered':`${t.etaMinutes} min`}</b>${t.status==='DELIVERED'?'Reached your location':'Estimated arrival'}</span><span><b>${t.progressPercent}%</b>${esc(t.status.replaceAll('_',' '))}</span><span><b>${Math.floor(t.remainingSeconds/60)}:${String(t.remainingSeconds%60).padStart(2,'0')}</b>Simulation timer</span>`;$('#delivery-timeline').innerHTML=(t.timeline||[]).map(s=>`<span class="delivery-step ${s.complete?'complete':''}">${esc(s.status.replaceAll('_',' '))}</span>`).join('');if(t.status==='DELIVERED'){toast(`Order #${id} delivered`);await loadOrders();return}state.trackingTimer=setTimeout(refresh,5000)}catch(e){$('#tracking-details').innerHTML=`<div class="error-box"><b>Tracking unavailable</b>${esc(e.message)}</div>`}};refresh()}
async function openPayment(id){const o=state.orders.find(x=>+x.id===id);if(!o)return;const orderStatus=String(o.status||'').toLowerCase();if(['payment_failed','failed','cancelled'].includes(orderStatus)){toast('This order has no payable transaction. Create a new order with a valid amount.');return}const f=$('#payment-form');f.hidden=false;$('#payment-progress').hidden=true;f.reset();delete f.dataset.existingPayment;f.orderId.value=o.id;f.amount.value=o.totalAmount;$('#payment-order').textContent=`#${o.id}`;$('#payment-summary').innerHTML=`<b>Total due</b><span style="float:right;font-size:20px;font-weight:700">₹${Number(o.totalAmount).toFixed(2)}</span>${state.profile.upiId?`<small class="saved-upi">Saved test UPI · ${esc(state.profile.upiId)}</small>`:'<small class="saved-upi">Add a test UPI ID from your profile</small>'}`;$('#payment-modal').showModal();try{const data=await request(config.paths.paymentForOrder(o.id)),payment=Array.isArray(data)?data.at(-1):data;if(payment?.id||payment?.status){state.payments.set(+o.id,payment);f.dataset.existingPayment='true';f.hidden=true;$('#payment-progress').hidden=false;renderOrders();watchPayment(o.id)}else{$('.form-error',f).textContent='No payment exists for this order. Create a new order with a valid amount.'}}catch(e){$('.form-error',f).textContent=e.message} }
async function cancelOrder(id){if(!confirm(`Cancel order #${id}?`))return;try{await request(`${config.paths.orders}/${id}`,{method:'DELETE'});toast('Order cancelled');await loadOrders()}catch(e){toast(e.message)}}
function watchPayment(orderId){if(state.watchers.has(orderId))state.watchers.get(orderId)();let stopped=false,timer,stream;const update=p=>{if(!p?.status)return;state.payments.set(+orderId,p);renderOrders();const terminal=['paid','success','succeeded','completed','failed','cancelled'].includes(String(p.status).toLowerCase());if(terminal){toast(`Payment ${p.status}`);$('#payment-modal').close();stop()}};const handleEvent=e=>{try{update(JSON.parse(e.data))}catch{}};const poll=async()=>{if(stopped)return;try{const p=await request(config.paths.paymentForOrder(orderId));update(Array.isArray(p)?p.at(-1):p)}catch{}if(!stopped)timer=setTimeout(poll,2500)};try{const path=config.streamPath.replace('{id}',encodeURIComponent(orderId));stream=new EventSource(config.apiUrl+path);stream.onmessage=handleEvent;stream.addEventListener('payment-status',handleEvent);stream.onerror=()=>{stream.close();poll()}}catch{poll()}const stop=()=>{stopped=true;clearTimeout(timer);stream?.close();state.watchers.delete(orderId)};state.watchers.set(orderId,stop);setTimeout(()=>{if(!stopped)poll()},3000)}
function paintAvatar(element){const name=state.profile.name||state.profile.email||'Profile',initial=name.trim().charAt(0).toUpperCase()||'P';element.textContent=initial;element.style.backgroundImage=state.profile.photo?`url("${state.profile.photo}")`:'';element.classList.toggle('has-image',Boolean(state.profile.photo))}
function updateProfileUI(){const button=$('#profile-open');button.hidden=!state.token;if(!state.token)return;paintAvatar($('#profile-avatar-small'));paintAvatar($('#profile-avatar-large'));$('#profile-label').textContent=(state.profile.name||'Profile').split(' ')[0];const f=$('#profile-form');f.name.value=state.profile.name||'';f.email.value=state.profile.email||'';f.phone.value=state.profile.phone||'';f.upiId.value=state.profile.upiId||''}
async function loadIdentity(){if(!state.token)return;try{const me=await request(config.paths.me);state.profile={...state.profile,name:state.profile.name||me.name||'',email:me.email||state.profile.email||''};localStorage.setItem('plated_profile',JSON.stringify(state.profile));updateProfileUI()}catch{}}
function resizeProfilePhoto(file){return new Promise((resolve,reject)=>{if(!file.type.startsWith('image/'))return reject(new Error('Choose a PNG, JPEG, or WebP image'));if(file.size>5*1024*1024)return reject(new Error('Profile photo must be smaller than 5 MB'));const reader=new FileReader();reader.onerror=()=>reject(new Error('Could not read profile photo'));reader.onload=()=>{const img=new Image();img.onerror=()=>reject(new Error('Could not open profile photo'));img.onload=()=>{const canvas=document.createElement('canvas');canvas.width=256;canvas.height=256;const ctx=canvas.getContext('2d'),side=Math.min(img.width,img.height),sx=(img.width-side)/2,sy=(img.height-side)/2;ctx.drawImage(img,sx,sy,side,side,0,0,256,256);resolve(canvas.toDataURL('image/jpeg',.82))};img.src=reader.result};reader.readAsDataURL(file)})}
$$('[data-close]').forEach(b=>b.onclick=()=>{if(b.closest('#tracking-modal'))clearTimeout(state.trackingTimer);b.closest('dialog').close()});$$('dialog').forEach(d=>d.onclick=e=>{if(e.target===d){if(d.id==='tracking-modal')clearTimeout(state.trackingTimer);d.close()}});
$('#auth-open').onclick=()=>{if(state.token){state.token='';localStorage.removeItem('plated_token');$('#auth-open').textContent='Sign in';updateProfileUI();toast('Signed out')}else $('#auth-modal').showModal()};
$('#profile-open').onclick=()=>{updateProfileUI();$('#profile-form .form-error').textContent='';$('#profile-modal').showModal()};
$('#profile-form').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,b=$('button[type="submit"]',f),d=new FormData(f),upiId=String(d.get('upiId')||'').trim();if(upiId&&!/^[a-zA-Z0-9._-]{2,}@[a-zA-Z]{2,}$/.test(upiId)){$('.form-error',f).textContent='Enter a valid test UPI ID such as name@bank';return}pending(b,true);try{const file=f.photo.files[0],photo=file?await resizeProfilePhoto(file):state.profile.photo||'';state.profile={...state.profile,name:String(d.get('name')).trim(),email:String(d.get('email')).trim(),phone:String(d.get('phone')).trim(),upiId,photo};localStorage.setItem('plated_profile',JSON.stringify(state.profile));updateProfileUI();$('#profile-modal').close();toast('Test profile and UPI ID saved in this browser')}catch(x){$('.form-error',f).textContent=x.message}finally{pending(b,false)}};
$$('[data-auth-mode]').forEach(b=>b.onclick=()=>{state.authMode=b.dataset.authMode;$$('[data-auth-mode]').forEach(x=>x.classList.toggle('active',x===b));$('.register-field').hidden=state.authMode==='login';$('.register-field input').required=state.authMode==='register';$('#auth-heading').textContent=state.authMode==='login'?'Sign in':'Create account'});
$('#auth-form').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,b=$('button[type="submit"]',f),body=Object.fromEntries(new FormData(f));if(state.authMode==='login')delete body.name;pending(b,true);try{const data=await request(config.paths[state.authMode],{method:'POST',body:JSON.stringify(body)});if(data.success===false)throw new Error(data.message);if(state.authMode==='register'){toast('Account created. Sign in now.');$('[data-auth-mode="login"]').click()}else{state.token=data.token;localStorage.setItem('plated_token',data.token);$('#auth-open').textContent='Sign out';$('#auth-modal').close();await loadIdentity();toast('Welcome back')}}catch(x){$('.form-error',f).textContent=x.message}finally{pending(b,false)}};
$('#apply-coupon').onclick=()=>{const value=$('#order-form').coupon.value.trim().toUpperCase();state.coupon=value==='WELCOME10'?value:'';toast(state.coupon?'WELCOME10 applied':'Use test code WELCOME10');renderPrice()};
$('#order-form').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,b=$('button[type="submit"]',f),d=new FormData(f),pricing=priceOrder(),selected=testMenu.filter(item=>(state.cart.get(item.id)||0)>0);if(!selected.length){$('.form-error',f).textContent='Add at least one food item';return}const body={restaurantId:+d.get('restaurantId'),totalAmount:+pricing.total,subtotal:+pricing.subtotal,discountAmount:+pricing.discount,deliveryFee:+pricing.deliveryFee,itemSummary:selected.map(item=>`${item.name} × ${state.cart.get(item.id)}`).join(', '),deliveryLatitude:state.location.latitude,deliveryLongitude:state.location.longitude,deliveryAddress:d.get('deliveryAddress')};localStorage.setItem('plated_address',body.deliveryAddress);pending(b,true);try{await request(config.paths.orders,{method:'POST',body:JSON.stringify(body)});$('#order-modal').close();toast('Order placed with food items and driver assigned');await loadOrders()}catch(x){$('.form-error',f).textContent=x.message}finally{pending(b,false)}};
$('#payment-form').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,b=$('button[type="submit"]',f),d=new FormData(f),key=crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`,method=d.get('paymentMethod'),body={orderId:+d.get('orderId'),amount:+d.get('amount'),paymentMethod:method,upiId:method==='UPI'?(state.profile.upiId||''):undefined,idempotencyKey:key};if(method==='UPI'&&!body.upiId){$('.form-error',f).textContent='Add a test UPI ID from your profile first';return}pending(b,true);try{let payment=state.payments.get(body.orderId);if(!payment){const result=await request(config.paths.payments,{method:'POST',headers:{'Idempotency-Key':key},body:JSON.stringify(body)});payment=result.payment||result}state.payments.set(body.orderId,payment);f.hidden=true;$('#payment-progress').hidden=false;watchPayment(body.orderId);renderOrders()}catch(x){$('.form-error',f).textContent=x.message}finally{pending(b,false)}};
$('#search').onsubmit=e=>{e.preventDefault();const q=$('#query').value.toLowerCase();renderRestaurants(state.restaurants.filter(r=>`${r.name} ${r.address}`.toLowerCase().includes(q)));$('.restaurants').scrollIntoView()};$('#query').oninput=e=>{if(!e.target.value)renderRestaurants()};$$('.category-card').forEach(button=>button.onclick=()=>{state.preselectedItem=button.dataset.menuItem;toast(`${testMenu.find(item=>item.id===state.preselectedItem)?.name} selected — choose a restaurant`);$('.restaurants').scrollIntoView()});$('#browse-offer').onclick=()=>{$('.restaurants').scrollIntoView();toast('Use WELCOME10 during checkout')};$('#rating-filter').onclick=()=>{state.ratingOnly=!state.ratingOnly;$('#rating-filter').classList.toggle('active',state.ratingOnly);renderRestaurants()};$('#show-favourites').onclick=()=>{state.favouritesOnly=!state.favouritesOnly;$('#show-favourites').textContent=state.favouritesOnly?'Show all':'♡ Favourites';$('#show-favourites').classList.toggle('active',state.favouritesOnly);renderRestaurants()};$('#refresh').onclick=loadRestaurants;$('#reload-orders').onclick=loadOrders;$('#new-order').onclick=()=>openOrder();
function saveLocation(latitude,longitude,label){state.location={latitude,longitude,label};localStorage.setItem('plated_location',JSON.stringify(state.location));$('#location-status').textContent=`${label} · ${latitude.toFixed(5)}, ${longitude.toFixed(5)}`;renderRestaurants()}
async function discoverNearby(latitude,longitude){if(state.discovering)return;state.discovering=true;const buttons=[$('#use-location'),$('#demo-location')];buttons.forEach(b=>b.disabled=true);$('#location-status').textContent='Finding nearby restaurants…';try{const result=await request(config.paths.discover(latitude,longitude));state.location.label=result.city||state.location.label;localStorage.setItem('plated_location',JSON.stringify(state.location));await loadRestaurants();$('#location-status').textContent=`${state.location.label} · ${latitude.toFixed(5)}, ${longitude.toFixed(5)} · ${result.discovered} nearby`;toast(result.imported?`${result.imported} new restaurants imported`:`Nearby restaurants refreshed`)}catch(e){await loadRestaurants();$('#location-status').textContent=`${state.location.label} · provider unavailable · showing saved restaurants`;toast('Live discovery is busy; saved restaurants are shown. Try again shortly.')}finally{state.discovering=false;buttons.forEach(b=>b.disabled=false)}}
function selectAndDiscover(latitude,longitude,label){saveLocation(latitude,longitude,label);discoverNearby(latitude,longitude)}
$('#use-location').onclick=()=>{if(!navigator.geolocation){toast('Location is not supported by this browser');return}$('#location-status').textContent='Requesting browser location…';navigator.geolocation.getCurrentPosition(p=>selectAndDiscover(p.coords.latitude,p.coords.longitude,'Live GPS location'),e=>{$('#location-status').textContent='Location permission was not granted';toast(e.message)},{enableHighAccuracy:true,timeout:10000,maximumAge:30000})};
$('#demo-location').onclick=()=>selectAndDiscover(12.9716,77.5946,'Bengaluru test location');
$('#settings-open').onclick=()=>{const f=$('#settings-form');f.apiUrl.value=config.apiUrl;f.streamPath.value=config.streamPath;$('#settings-modal').showModal()};$('#settings-form').onsubmit=e=>{e.preventDefault();const d=new FormData(e.currentTarget);localStorage.setItem('plated_api_url',d.get('apiUrl').replace(/\/$/,''));localStorage.setItem('plated_stream_path',d.get('streamPath'));location.reload()};
if(state.token)$('#auth-open').textContent='Sign out';updateProfileUI();if(state.token)loadIdentity();if(state.location)$('#location-status').textContent=`${state.location.label||'Saved location'} · ${Number(state.location.latitude).toFixed(5)}, ${Number(state.location.longitude).toFixed(5)}`;health();Promise.all([loadRestaurants(),loadOrders()]);
