'use strict';
const apiUrl=localStorage.getItem('plated_api_url')||'http://localhost:8085';
const token=localStorage.getItem('plated_token')||'';
const orderId=Number(new URLSearchParams(location.search).get('orderId'));
const $=selector=>document.querySelector(selector);
const key=`plated_payment_${orderId}`;
let payment,order;
function save(status,message=''){localStorage.setItem(key,JSON.stringify({status,message,updatedAt:Date.now()}))}
async function request(path,options={}){const headers={Accept:'application/json',...(options.body?{'Content-Type':'application/json'}:{}),...(token?{Authorization:`Bearer ${token}`}:{})};let response;try{response=await fetch(apiUrl+path,{...options,headers})}catch{throw new Error(`Cannot reach FoodService API at ${apiUrl}`)}const text=await response.text();let data;try{data=text?JSON.parse(text):{}}catch{data={message:text}}if(!response.ok)throw new Error(data.message||`Request failed (${response.status})`);return data}
function showResult(kind,title,copy,retry=false){$('#loading').hidden=true;$('#checkout').hidden=true;$('#result').hidden=false;$('#result-icon').textContent=kind==='success'?'✓':'!';$('#result-title').textContent=title;$('#result-copy').textContent=copy;$('#retry').hidden=!retry}
async function load(){if(!Number.isInteger(orderId)||orderId<=0){save('failed','Invalid order');showResult('error','Invalid payment link','Return to FoodService and choose Pay now again.');return}if(!token){save('failed','Sign-in required');showResult('error','Please sign in','Return to FoodService, sign in, and open payment again.');return}try{[order,payment]=await Promise.all([request(`/orders/${orderId}`),request(`/payments/order/${orderId}`)]);if(String(payment.status).toLowerCase()==='succeeded'){save('succeeded');showResult('success','Payment already verified','Your payment was already completed. Driver tracking is now available.');return}$('#order-number').textContent=`#${orderId}`;$('#amount').textContent=`₹${Number(order.totalAmount).toFixed(2)}`;$('#items').textContent=order.itemSummary||'Food order';$('#loading').hidden=true;$('#checkout').hidden=false;save('in_progress')}catch(error){save('failed',error.message);showResult('error','Checkout unavailable',error.message,true)}}
async function begin(){const button=$('#pay');$('#error').textContent='';button.disabled=true;button.textContent='Connecting securely…';save('in_progress');try{if(typeof Razorpay!=='function')throw new Error('Razorpay Checkout could not load. Check your internet connection.');const provider=await request('/payments/razorpay/order',{method:'POST',body:JSON.stringify({transactionId:payment.transactionId})});const checkout=new Razorpay({key:provider.keyId,amount:provider.amount,currency:provider.currency,order_id:provider.providerOrderId,name:'Plated FoodService',description:`Test payment for order #${orderId}`,theme:{color:'#155b45'},method:{upi:true,card:true,netbanking:false,wallet:false,paylater:false},handler:async result=>{try{const verified=await request('/payments/razorpay/verify',{method:'POST',body:JSON.stringify({transactionId:payment.transactionId,...result})});if(String(verified.status).toLowerCase()!=='succeeded')throw new Error('Backend did not confirm payment success');save('succeeded');showResult('success','Payment verified','Your test payment is complete. A driver can now be assigned and tracked.')}catch(error){save('failed',error.message);showResult('error','Verification failed',error.message,true)}},modal:{ondismiss:()=>{save('failed','Checkout closed before completion');$('#error').textContent='Checkout was closed. No driver was assigned; you can safely retry.';button.disabled=false;button.textContent='Retry Razorpay Test Checkout'}}});checkout.on('payment.failed',event=>{const message=event.error?.description||'Razorpay reported a failed test payment';save('failed',message);$('#error').textContent=`${message}. No driver was assigned.`;button.disabled=false;button.textContent='Retry Razorpay Test Checkout'});checkout.open()}catch(error){save('failed',error.message);$('#error').textContent=error.message;button.disabled=false;button.textContent='Retry Razorpay Test Checkout'}}
$('#pay').onclick=begin;$('#retry').onclick=()=>location.reload();load();
